version: "3.5"
services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: app

volumes:
  dbdata:
